# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "Highlightr", "1.1.0"
  pod "AZDropdownMenu" 
  # Pods for Quark

  target 'QuarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuarkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
